[package]
name = "winter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.3"
unicode-width = "0.1.10"

[target.'cfg(target_os = "macos")'.dependencies]
crossterm = "0.28.1"
